server:
  port: 8085
spring:
  profiles.active: prod

  application:
    name: notification-service
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,refresh
  endpoint:
    prometheus:
      enabled: true
  security:
    enabled: false
